DROP TABLE IF EXISTS srs;

CREATE TABLE srs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  is_completed INTEGER NOT NULL DEFAULT 0,
  file_url TEXT DEFAULT ''
);

